import {sb,resolveContentContext,normalizeContentPayload,logoutContentVault} from './content-vault-client.js';
import {model,fields,filterItems,related,safeUrl,validatePackage,sha256} from './content-library-model.mjs';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let ctx,items=[],filtered=[],view='cards',draft=null,current=null,ready=false,firstOptions=true;
const params=new URLSearchParams(location.search), filterKeys=['q',...Object.keys(fields),'from','to'];
const notify=text=>{$('notice').textContent=text;$('notice').hidden=false;setTimeout(()=>$('notice').hidden=true,5000)};
const stamp=s=>s?new Date(s).toLocaleString('es-PE',{timeZone:'America/Lima',dateStyle:'medium',timeStyle:'short'}):'No registrada';
const facts=pairs=>'<div class="facts">'+pairs.map(([k,v])=>`<div><small>${esc(k)}</small><b>${esc(v||'Sin registrar')}</b></div>`).join('')+'</div>';
$('selectFilters').innerHTML=Object.entries(fields).map(([k,label])=>`<div><label for="${k}">${label}</label><select id="${k}"><option value="">Todos</option></select></div>`).join('');
for(const k of filterKeys){$(k).value=params.get(k)||'';$(k).addEventListener(k==='q'?'input':'change',render)}
function filters(){return Object.fromEntries(filterKeys.map(k=>[k,$(k).value]))}
function syncUrl(){const p=new URLSearchParams();if(ctx)p.set('negocio',ctx.negocioId);for(const [k,v] of Object.entries(filters()))if(v)p.set(k,v);if(current)p.set('pieza',current.id);if(view==='table')p.set('vista','tabla');history.replaceState(null,'',`${location.pathname}?${p}`)}
function options(){for(const k of Object.keys(fields)){const selected=firstOptions?(params.get(k)||''):$(k).value;const values=[...new Set(items.map(x=>x[k]))].sort((a,b)=>a.localeCompare(b,'es'));if(selected&&!values.includes(selected))values.push(selected);$(k).innerHTML='<option value="">Todos</option>'+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');$(k).value=selected}firstOptions=false}
function render(){
 if(!ready)return;const f=filters();filtered=filterItems(items,f);if(f.from&&f.to&&f.from>f.to){$('error').hidden=false;$('error').textContent='La fecha inicial debe ser anterior a la final.'}else{$('error').hidden=true}
 $('count').textContent=`${filtered.length} de ${items.length} piezas · historial de la marca seleccionada`;
 $('activeFilters').innerHTML=Object.entries(f).filter(([,v])=>v).map(([k,v])=>`<button data-clear="${k}">${esc(fields[k]||({q:'Búsqueda',from:'Desde',to:'Hasta'})[k])}: ${esc(v)} ×</button>`).join('');
 $('cardsView').setAttribute('aria-pressed',view==='cards');$('tableView').setAttribute('aria-pressed',view==='table');
 if(!filtered.length){$('list').innerHTML='<div class="empty"><b>No hay piezas para esta selección</b>Prueba quitando un filtro o importa un guion aprobado.</div>';syncUrl();return}
 if(view==='cards')$('list').innerHTML='<div class="grid">'+filtered.map(x=>`<article class="card"><div class="cardtop"><span class="code">${esc(x.content_code)}</span><span class="status">${esc(x.status)}</span></div><h3>${esc(x.title)}</h3><div class="chips"><span class="chip">${esc(x.business)}</span><span class="chip">${esc(x.type)}</span></div><p>${esc(x.tema||'Situación pendiente de clasificar')}</p><div class="chips"><span class="chip">${esc(x.service)}</span><span class="chip">${esc(x.objective)}</span><span class="chip">${esc(x.audience)}</span></div><div class="cardfoot"><span>${esc(x.hook)} · ${esc(x.version)}</span><button data-open="${esc(x.id)}">Ver guion y ruta →</button></div></article>`).join('')+'</div>';
 else $('list').innerHTML='<div class="tablewrap"><table><thead><tr>'+['Hook / título','Negocio objetivo','Servicio','Tema','Objetivo','Audiencia','Hook / familia','Estado'].map(x=>`<th>${x}</th>`).join('')+'</tr></thead><tbody>'+filtered.map(x=>`<tr><td><button data-open="${esc(x.id)}">${esc(x.title)}</button></td>${[x.business,x.service,x.type,x.objective,x.audience,x.hook+' · '+x.family,x.status].map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')+'</tbody></table></div>';
 syncUrl();
}
function openPiece(id){
 const x=items.find(x=>x.id===id);if(!x)return;current=x;const e=x.engine;
 $('detailTitle').textContent=x.title;$('pieceCode').textContent=`${x.content_code||''} · ${x.version} · ${x.status}`;
 const sources=Array.isArray(e.sources)?e.sources:[];const route=Array.isArray(e.production_route)?e.production_route:[];
 const relatives=related(items,x);const versions=items.filter(v=>v.id===x.id||v.parent_content_id===x.id||x.parent_content_id===v.id||(x.parent_content_id&&v.parent_content_id===x.parent_content_id));
 $('detailBody').innerHTML=facts([['Negocio objetivo',x.business],['Servicio',x.service],['Tipo de tema',x.type],['Objetivo',x.objective],['Temperatura',x.audience],['Relación previa',x.relationship]])+
 `<section class="section"><h3>Guion aprobado</h3><button id="copyScript">Copiar guion</button><div class="script">${esc(x.master_script)}</div></section>`+
 `<section class="section"><h3>Por qué se creó</h3><p><b>Situación:</b> ${esc(x.tema)}</p><p><b>Enfoque:</b> ${esc(x.angulo)}</p><p><b>Recompensa:</b> ${esc(x.payoff)}</p>${facts([['ID del hook',x.hook],['Familia',x.family],['Plantilla',x.hook_template]])}<p>${esc(e.audit_summary||'Sin auditoría registrada en esta ficha.')}</p></section>`+
 `<section class="section"><h3>Ruta de producción</h3>${route.length?route.map(s=>`<div class="route"><small>${esc(s.time||'Sin tiempo estimado')}</small><p>${esc(s.speech)}</p><p class="visual"><b>Se ve:</b> ${esc(s.visual)}</p><p class="visual"><b>Acción:</b> ${esc(s.action)}</p></div>`).join(''):'<p>Ruta pendiente de registrar. El guion aprobado se conserva completo.</p>'}<h4>Antes de grabar</h4><ul>${(e.production_checklist||[]).map(v=>`<li>${esc(v)}</li>`).join('')}</ul><p><b>Pendiente:</b> ${esc(e.production_pending||'No registrado')}</p></section>`+
 `<section class="section"><h3>Fuentes y límites</h3>${sources.length?sources.map(s=>`<p>${safeUrl(s.url)?`<a href="${esc(safeUrl(s.url))}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`:esc(s.title)}<br><small>${esc(s.evidence_type)} · ${esc(s.limitation)}</small></p>`).join(''):'<p>No hay fuentes estructuradas en esta pieza antigua.</p>'}</section>`+
 `<section class="section"><h3>Aprobación y trazabilidad</h3>${facts([['Versión',x.version],['Aprobación original',stamp(e.approval?.approved_at)],['Registro',stamp(x.created_at)]])}<p>${esc(e.approval?.context||'Sin contexto de aprobación registrado.')}</p><p><b>Respuesta:</b> ${esc(e.approval?.text||'No registrada')}</p><details><summary>Huella del texto aprobado</summary><p style="overflow-wrap:anywhere">${esc(e.script_sha256||'No registrada')}</p></details><h4>Versiones vinculadas</h4>${versions.map(v=>`<button class="related" data-open="${esc(v.id)}">${esc(v.version)} · ${esc(v.title)}</button>`).join('')}</section>`+
 `<section class="section"><h3>Contenido relacionado (${relatives.length})</h3><p>Coincidencias de clasificación. Revisa también la pregunta, la respuesta y el ejemplo para evaluar repetición.</p>${relatives.map(({item:v,reasons})=>`<button class="related" data-open="${esc(v.id)}">${esc(v.title)}<small>${esc(reasons.join(' · '))}</small></button>`).join('')||'<p>Sin antecedentes relacionados en el registro consultado.</p>'}</section>`;
 $('copyScript').onclick=async()=>{try{await navigator.clipboard.writeText(x.master_script||'');notify('Guion copiado.')}catch{notify('No se pudo copiar. Puedes seleccionar el texto del guion.')}};
 if(!$('detail').open)$('detail').showModal();syncUrl();
}
document.addEventListener('click',ev=>{const open=ev.target.closest('[data-open]');if(open)openPiece(open.dataset.open);const clear=ev.target.closest('[data-clear]');if(clear){$(clear.dataset.clear).value='';render()}});
$('closeDetail').onclick=()=>$('detail').close();$('detail').addEventListener('close',()=>{current=null;syncUrl()});
$('clear').onclick=()=>{filterKeys.forEach(k=>$(k).value='');render()};$('cardsView').onclick=()=>{view='cards';render()};$('tableView').onclick=()=>{view='table';render()};$('logout').onclick=logoutContentVault;
function download(name,data){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$('export').onclick=()=>{if(!ready)return;download('historial-contenido.json',{schema_version:'1.1',negocio_id:ctx.negocioId,exported_at:new Date().toISOString(),filters:filters(),items:filtered.map(({engine,title,business,service,type,objective,audience,relationship,family,hook,status,version,...row})=>row)});notify('Historial filtrado exportado.')};
async function reload(){
 const all=[];for(let offset=0;;offset+=500){const {data,error}=await sb.from('content_piezas').select('*').eq('negocio_id',ctx.negocioId).order('created_at',{ascending:false}).order('id').range(offset,offset+499);if(error)throw error;all.push(...data);if(data.length<500)break}
 items=all.map(model);options();$('stats').innerHTML=[['Piezas registradas',items.length],['Guiones aprobados',items.filter(x=>x.estado==='APPROVED').length],['Publicadas o medidas',items.filter(x=>['PUBLISHED','MEASURED','WINNER','NORMAL','LOSER'].includes(x.estado)).length],['Negocios objetivo',new Set(items.map(x=>x.business).filter(x=>x!=='Sin clasificar')).size]].map(([label,n])=>`<div class="stat"><b>${n}</b><span>${label}</span></div>`).join('');ready=true;render();
}
$('importButton').onclick=()=>{draft=null;$('file').value='';$('confirmApproval').checked=false;$('saveImport').disabled=true;$('importPreview').textContent='';$('importError').textContent='';$('importDialog').showModal()};$('closeImport').onclick=()=>$('importDialog').close();
$('file').onchange=async()=>{draft=null;$('saveImport').disabled=true;$('confirmApproval').checked=false;$('importPreview').textContent='';try{const f=$('file').files[0];if(!f)return;if(f.size>2_000_000)throw Error('El expediente supera 2 MB.');const p=await validatePackage(JSON.parse(await f.text()));if(p.negocio_id&&p.negocio_id!==ctx.negocioId)throw Error('Este expediente pertenece a otra marca. Selecciona la empresa correcta.');draft=p;$('importError').textContent='';$('importPreview').innerHTML=`<h3>${esc(p.titulo)}</h3>${facts([['Marca',ctx.negocio.nombre],['Negocio objetivo',p.metadata.content_engine_v1.target_business],['Tema',p.metadata.content_engine_v1.topic_type]])}<div class="script">${esc(p.master_script)}</div>`}catch(e){$('importError').textContent=e.message}};
$('confirmApproval').onchange=()=>{$('saveImport').disabled=!draft||!$('confirmApproval').checked};
$('saveImport').onclick=async()=>{
 if(!draft||!ctx.canEdit||!$('confirmApproval').checked)return;$('saveImport').disabled=true;
 try{
  const p=await validatePackage(draft),e=p.metadata.content_engine_v1;
  const existing=await sb.from('content_piezas').select('*').eq('negocio_id',ctx.negocioId).eq('sync_key',p.sync_key).maybeSingle();if(existing.error)throw existing.error;
  if(existing.data){if(existing.data.master_script!==p.master_script||existing.data.metadata?.content_engine_v1?.script_sha256!==e.script_sha256)throw Error('La identidad ya existe con otro texto. Crea una revisión; no se sobrescribió nada.');$('importDialog').close();await reload();openPiece(existing.data.id);notify('Esta versión ya estaba guardada. No se duplicó.');return}
  if(p.parent_content_id){const parent=await sb.from('content_piezas').select('id').eq('negocio_id',ctx.negocioId).eq('id',p.parent_content_id).single();if(parent.error)throw Error('La revisión no tiene una pieza anterior válida en esta marca.')}
  const payload=normalizeContentPayload(p,ctx.negocioId);payload.created_by=ctx.user.id;payload.sync_key=p.sync_key;if(p.parent_content_id)payload.parent_content_id=p.parent_content_id;
  payload.metadata={...payload.metadata,content_engine_v1:{...e,approval:{...e.approval,recorded_at:new Date().toISOString()},import_confirmed_by:ctx.user.id}};
  const result=await sb.from('content_piezas').insert(payload).select('*').single();if(result.error)throw result.error;
  const check=await sb.from('content_piezas').select('*').eq('negocio_id',ctx.negocioId).eq('id',result.data.id).single();if(check.error)throw check.error;if(check.data.master_script!==p.master_script||await sha256(check.data.master_script)!==e.script_sha256)throw Error('Guardado recibido, pero la verificación del texto falló. Revisa el registro antes de reintentar.');
  $('importDialog').close();await reload();openPiece(check.data.id);notify('Guion aprobado guardado y releído correctamente.');
 }catch(e){$('importError').textContent=(e.message||'No se pudo guardar.')+' Puedes reintentar: se comprobará la identidad antes de insertar.'}finally{$('saveImport').disabled=!draft||!$('confirmApproval').checked}
};
async function init(){try{
 ctx=await resolveContentContext({redirect:false});if(params.get('negocio')&&params.get('negocio')!==String(ctx.negocioId))throw Error('No tienes acceso a la marca solicitada. Abre tu panel y elige una empresa autorizada.');
 const {data,error}=await sb.from('negocios').select('id,nombre').in('id',ctx.memberships.map(x=>x.negocio_id));if(error)throw error;
 $('company').innerHTML=data.map(n=>`<option value="${esc(n.id)}">${esc(n.nombre)}</option>`).join('');$('company').value=ctx.negocioId;$('company').disabled=false;$('company').onchange=()=>{location.href=`./biblioteca-contenido.html?negocio=${encodeURIComponent($('company').value)}`};
 $('panelLink').href=`./cliente-panel.html?negocio=${encodeURIComponent(ctx.negocioId)}`;$('connection').textContent='Registro conectado · acceso por empresa';$('importButton').disabled=!ctx.canEdit;view=params.get('vista')==='tabla'?'table':'cards';await reload();if(params.get('pieza'))openPiece(params.get('pieza'));
 }catch(e){$('error').hidden=false;$('error').textContent=e.message||'No se pudo cargar la biblioteca.';$('connection').textContent='Registro no disponible';$('list').innerHTML='<div class="empty"><b>No pudimos consultar tu historial</b><a href="./cliente-acceso.html">Iniciar sesión</a> · <button onclick="location.reload()">Reintentar</button></div>';$('count').textContent='Historial sin consultar';$('export').disabled=true}}
init();
