import {sb,resolveContentContext} from './content-vault-client.js';
import {objectives,audiences,motivations,categories,formats,filterEpisodes,moveDate,episodeState,coverage,serviceMatches,relatedHistory,makeBrief} from './editorial-plan-model.mjs?v=20260917-colores';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const short=s=>s.toLowerCase().replace(/^./,c=>c.toUpperCase());
const categoryLabels={C1:'Identificación',C2:'Educación',C3:'Mitos',C4:'Criterio',C5:'Prueba real',C6:'Proceso',C7:'Objeciones / FAQ',C8:'Comparación',C9:'Acción'};
let ctx,record,plan,pieces=[],publications=[],selected=null,anchor='2026-09-21',saving=false;
const date=d=>new Date(d+'T12:00:00Z'),iso=d=>d.toISOString().slice(0,10),plus=(d,n)=>{const x=date(d);x.setUTCDate(x.getUTCDate()+n);return iso(x)};
const fmt=d=>date(d).toLocaleDateString('es-PE',{day:'numeric',month:'short',timeZone:'UTC'});
const filters=()=>Object.fromEntries(['service','audience','objective','motivation'].map(k=>[k,$(k).value]));
const state=e=>ctx.preview?{key:'planned',label:'Previsto'}:episodeState(e,pieces,publications,ctx.negocioId);
const seriesFor=e=>plan.series.find(s=>s.key===e.series);
const notify=s=>{$('notice').textContent=s;$('notice').hidden=false;setTimeout(()=>$('notice').hidden=true,6500)};
const safeUrl=s=>{try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:null}catch{return null}};
const openDialog=id=>{if(!$(id).open)$(id).showModal()};
const download=(name,content,type)=>{const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const badge=e=>{const s=state(e);return `<span class="badge ${s.key}">${esc(s.label)}</span>`};
function select(key,show=false){selected=key;render();if(show)details(key)}
function picklist(id,values,label){$(id).innerHTML=`<option value="">${label}</option>`+values.map(v=>`<option value="${esc(v.value??v)}">${esc(v.label??short(v))}</option>`).join('')}
function render(){
 const f=filters(),eps=filterEpisodes(plan,f);if(!eps.some(e=>e.key===selected))selected=eps.find(e=>state(e).key==='planned')?.key||eps[0]?.key||null;
 $('services').innerHTML=[{id:'',name:'Todos'},...plan.services].map(s=>`<button data-service="${s.id}" data-svc="${s.id}" class="${f.service===s.id?'active':''}"><span aria-hidden="true">${s.id?'◇':'▦'}</span><span>${esc(s.name)}</span></button>`).join('');
 const counts={published:0,approved:0,planned:0};for(const e of eps){const k=state(e).key;if(k==='published')counts.published++;else if(['approved','recorded'].includes(k))counts.approved++;else counts.planned++}
 $('stats').innerHTML=[[eps.length,'temas del plan','▤'],[ctx.preview?'—':counts.published,'publicados del plan','✓'],[ctx.preview?'—':counts.approved,'guiones aprobados¹','▣'],[ctx.preview?'—':counts.planned,'por desarrollar / revisar','◷']].map(([n,l,i])=>`<div class="stat"><span class="stat-icon" aria-hidden="true">${i}</span><div><b>${n}</b><small>${l}</small></div></div>`).join('');
 const weekends=eps.some(e=>e.reference_date>=anchor&&e.reference_date<=plus(anchor,13)&&[0,6].includes(date(e.reference_date).getUTCDay()));let dates=[];for(let i=0;i<14;i++){const d=plus(anchor,i);if(weekends||![0,6].includes(date(d).getUTCDay()))dates.push(d)}$('calendarGrid').style.gridTemplateColumns=`repeat(${weekends?7:5},minmax(100px,1fr))`;
 $('range').textContent=`${fmt(dates[0])} – ${fmt(dates.at(-1))} ${date(anchor).getUTCFullYear()}`;
 $('calendarGrid').innerHTML=(weekends?['LUN','MAR','MIÉ','JUE','VIE','SÁB','DOM']:['LUN','MAR','MIÉ','JUE','VIE']).map(d=>`<div class="dayname">${d}</div>`).join('')+dates.map(d=>`<div class="day"><time datetime="${d}">${date(d).getUTCDate()}</time>${eps.filter(e=>e.reference_date===d).map(e=>`<button data-episode="${e.key}" data-svc="${e.service}" class="slot ${state(e).key} ${e.key===selected?'selected':''}" aria-label="${esc(e.title)}, parte ${e.part} de ${e.total}, ${esc(state(e).label)}"><b>${esc(e.title)}</b><small>${esc(plan.services.find(s=>s.id===e.service).name)} · ${e.part}/${e.total}</small><span class="state">${state(e).label}</span></button>`).join('')}</div>`).join('');
 const outside=eps.filter(e=>!dates.includes(e.reference_date)).length;$('offscreen').textContent=`${outside} temas fuera de estas dos semanas · Ampliar después del último tema previsto: ${plan.services.filter(s=>!f.service||s.id===f.service).map(s=>{const last=plan.episodes.filter(e=>e.service===s.id&&e.reference_date).map(e=>e.reference_date).sort().at(-1);return esc(s.name)+': '+(last?fmt(plus(last,1)):'sin fecha')}).join(' · ')}`;
 const groups=plan.series.filter(s=>eps.some(e=>e.series===s.key));$('seriesSummary').textContent=`${groups.length} colecciones · numeración fija por edición`;
 $('series').innerHTML=groups.map(s=>{const all=plan.episodes.filter(e=>e.series===s.key),visible=eps.filter(e=>e.series===s.key),done=all.filter(e=>state(e).key==='published').length;return `<details data-svc="${all[0]?.service||''}" ${visible.some(e=>e.key===selected)?'open':''}><summary><div><b>${esc(s.title)}</b><small>${ctx.preview?s.size+' episodios previstos':done+' de '+s.size+' publicados'}${visible.length!==s.size?` · ${visible.length} visibles con filtros`:''}</small></div><span class="dots" aria-hidden="true">${all.map(e=>`<i class="${state(e).key}"></i>`).join('')}</span></summary>${visible.map(e=>`<button data-episode="${e.key}" data-svc="${e.service}" class="episode-row ${e.key===selected?'current':''}"><span class="part">${e.part}/${e.total}</span><b>${esc(e.title)}</b><span class="badge ${state(e).key}">${state(e).key==='planned'?(ctx.preview?'Previsto':'Pendiente'):esc(state(e).label)}</span></button>`).join('')}</details>`}).join('')||'<p class="empty">No hay temas para esta combinación. Revisa la cobertura o quita filtros.</p>';
 renderUsed(f);
 const ep=plan.episodes.find(e=>e.key===selected);
 $('nextStep').closest('.next-card').dataset.svc=ep?.service||'';
 $('service').dataset.svc=f.service||'';
 $('nextStep').innerHTML=ep?`<h3>${esc(ep.title)}</h3><p>${esc(plan.services.find(s=>s.id===ep.service).name)} · ${short(ep.audience)} · ${short(ep.objective)} · ${short(ep.motivation)}</p><p>${esc(seriesFor(ep).title)} · ${ep.part}/${ep.total}</p>${badge(ep)}${!ctx.preview&&relatedHistory(ep,pieces).some(x=>x.overlap>=2)?'<p class="gap">Hay antecedentes con temas parecidos. Compáralos antes de pedir otro guion.</p>':''}<p>${ep.reference_date?`Referencia: ${fmt(ep.reference_date)}`:'Sin fecha'} · ${esc(ep.evidence_status)}</p><button class="primary" data-brief="${ep.key}">Preparar pedido de guion A/B/C</button><button class="text-button" data-detail="${ep.key}">Ver ficha, ajustar fecha o vincular guion →</button>`:'<p class="empty">Esta combinación aún no tiene una pieza propuesta.</p>';
 if(ctx.preview){$('edition').textContent='VISTA PREVIA · SOLO LECTURA';$('planNote').textContent='Vista previa del plan propuesto. No se consulta el historial privado, no se guardan cambios ni se muestran aprobaciones. Entra desde tu panel para trabajar con los datos reales.';return}const unlinked=pieces.filter(p=>!plan.episodes.some(e=>e.content_id===p.id)).length;
 $('planNote').textContent=`¹ Contadores de piezas vinculadas a este plan; los publicados se cuentan aparte. ${unlinked} antecedentes de biblioteca aún sin vincular. ${plan.cadence} Las propuestas A/B/C no multiplican episodios. Última lectura del historial: ${new Date().toLocaleTimeString('es-PE')}.`;
 const p=new URLSearchParams({negocio:ctx.negocioId});for(const [k,v] of Object.entries(f))if(v)p.set(k,v);if(selected)p.set('tema',selected);history.replaceState(null,'',location.pathname+'?'+p);
}
function actualFor(f){return pieces.filter(p=>(!f.service||serviceMatches(p,f.service))&&(!f.audience||p.temperatura===f.audience)&&(!f.objective||p.objetivo===f.objective)&&(!f.motivation||(p.metadata?.content_engine_v1?.topic_type||p.metadata?.editorial_context_v1?.motivation)===f.motivation))}
function renderUsed(f){const actual=actualFor(f);$('usedSummary').textContent=ctx.preview?'Vista previa: historial privado no consultado.':`En ${actual.length} piezas registradas para estos filtros; pueden incluir guiones aún no publicados.`;
 const count=(key,v)=>actual.filter(p=>String(p[key]||'').startsWith(v)).length;
 const motiveCounts=motivations.map(v=>[short(v),actual.filter(p=>(p.metadata?.content_engine_v1?.topic_type||p.metadata?.editorial_context_v1?.motivation)===v).length]);
 const cats=categories.map(v=>[categoryLabels[v],count('categoria',v)]).filter(x=>x[1]);const hooks=plan.hook_families.map(v=>[v.id,count('hook_family',v.id)]).filter(x=>x[1]);
 $('used').innerHTML=[['Motivaciones',motiveCounts],['Categorías',cats.length?cats:[['Sin uso registrado',0]]],['Familias de hook',hooks.length?hooks:[['Sin uso registrado',0]]]].map(([label,vals])=>`<div><b>${label}</b>${vals.map(([v,n])=>`<span class="chip ${n?'':'zero'}">${esc(v)} · ${n}</span>`).join('')}</div>`).join('');
 if(ctx.preview){$('used').innerHTML='<p class="empty">El uso real aparece al entrar con tu cuenta.</p>';$('gap').textContent='Sin lectura de historial en esta vista.';return}const unknown=actual.filter(p=>!p.metadata?.content_engine_v1?.topic_type&&!p.metadata?.editorial_context_v1?.motivation).length;$('gap').textContent=unknown?`${unknown} piezas sin motivación clasificada. Cero no confirma ausencia.`:'Consulta los huecos del plan y del historial.';
}
function details(key){const e=plan.episodes.find(x=>x.key===key);if(!e)return;selected=key;$('details').dataset.svc=e.service;const hist=relatedHistory(e,pieces),svc=plan.services.find(s=>s.id===e.service);$('detailBody').innerHTML=`<h2 id="detailTitle">${esc(e.title)}</h2><p>${esc(seriesFor(e).title)} · parte ${e.part} de ${e.total} · ${esc(svc.name)}</p>${badge(e)}<div class="callout"><b>Pregunta que resolverá</b><p>${esc(e.question)}</p></div><div class="facts">${[['Objetivo',e.objective],['Audiencia',e.audience],['Relación',e.relationship],['Motivación',e.motivation],['Categoría',categoryLabels[e.category]],['Formato',e.format]].map(([k,v])=>`<div><small>${k}</small>${esc(v)}</div>`).join('')}</div><p><b>Situación propuesta:</b> ${esc(e.signal)}</p><p><b>Qué distingue esta pieza:</b> ${esc(e.payoff)}</p><p><b>Hooks:</b> ${e.hook_candidates.map(k=>esc(plan.hook_families.find(f=>f.id===k)?.name||k)).join(' · ')}. ${esc(e.hook_status)}</p><h3>Fuentes y pendientes</h3><p>${esc(e.evidence_status)}. Respuesta clínica y auditoría del guion pendientes.</p><ul>${e.source_ids.map(id=>{const s=plan.sources.find(x=>x.id===id);return s?`<li><a href="${esc(safeUrl(s.url)||'#')}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a><br>${esc(s.access)}. ${esc(s.scope)}</li>`:''}).join('')}</ul><details><summary>Límites de esta pieza</summary><ul>${e.limits.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details><label class="field">Fecha referencial ajustable<input id="editDate" type="date" value="${e.reference_date||''}" ${ctx.canEdit?'':'disabled'}></label><div class="actions"><button class="outline" id="saveDate" ${ctx.canEdit?'':'disabled'}>Guardar fecha</button><button class="primary" data-brief="${e.key}">Preparar pedido A/B/C</button></div><h3>Antecedentes de este servicio</h3><p>Comparar pregunta, respuesta y recompensa. La similitud de título no decide por sí sola si es repetición.</p><div class="history-list">${hist.map(({piece:p})=>`<div class="history-item"><a href="./biblioteca-contenido.html?negocio=${encodeURIComponent(ctx.negocioId)}&pieza=${encodeURIComponent(p.id)}">${esc(p.content_code)} · ${esc(p.titulo)}</a><small>${esc(p.estado)} · ${esc(p.objetivo)} · ${esc(p.temperatura)} · ${esc(p.hook_family||'Hook no clasificado')}</small></div>`).join('')||(ctx.preview?'<p>Historial no consultado en esta vista previa.</p>':'<p>No hay antecedentes registrados de este servicio en la lectura actual.</p>')}</div><label class="field">Vincular una pieza existente de biblioteca<select id="linkedId" ${ctx.canEdit?'':'disabled'}><option value="">Sin vincular</option>${hist.map(({piece:p})=>`<option value="${p.id}" ${p.id===e.content_id?'selected':''}>${esc(p.content_code+' · '+p.titulo)}</option>`).join('')}</select></label><p>Vincula solo si corresponde a esta pregunta. La aprobación y publicación se leen de la pieza real; esta acción no las concede.</p><button class="outline" id="saveLink" ${ctx.canEdit?'':'disabled'}>Guardar vínculo</button>`;
 $('saveDate').onclick=async()=>{try{const next=moveDate(plan,e.key,$('editDate').value||null);await persist(next);details(e.key);notify('Fecha guardada y verificada. La numeración se conserva.')}catch(err){notify(err.message)}};
 $('saveLink').onclick=async()=>{try{const id=$('linkedId').value||null;if(id&&plan.episodes.some(x=>x.key!==e.key&&x.content_id===id))throw Error('Esta pieza ya está vinculada a otro episodio.');const next=structuredClone(plan);next.episodes.find(x=>x.key===e.key).content_id=id;await persist(next);details(e.key);notify('Vínculo guardado. Los estados proceden de la biblioteca.')}catch(err){notify(err.message)}};openDialog('details');}
async function persist(next){if(!ctx.canEdit)throw Error('Tu rol permite consultar, pero no editar el plan.');if(saving)throw Error('Hay un cambio guardándose. Espera un momento.');saving=true;try{const {data,error}=await sb.from('content_planes_editoriales').update({document:next}).eq('id',record.id).eq('negocio_id',ctx.negocioId).eq('revision',record.revision).select('id,negocio_id,plan_key,document,revision,updated_at').maybeSingle();if(error)throw error;if(!data)throw Error('Otra sesión modificó el plan. Recarga antes de guardar; tus cambios no se sobrescribieron.');const {data:verified,error:readError}=await sb.from('content_planes_editoriales').select('id,negocio_id,plan_key,document,revision,updated_at').eq('id',record.id).eq('negocio_id',ctx.negocioId).single();if(readError)throw Error('El cambio fue enviado, pero no se pudo verificar. Recarga el plan.');record=verified;plan=verified.document;render()}finally{saving=false}}
function brief(key){const e=plan.episodes.find(x=>x.key===key);if(!e)return;selected=key;$('briefText').value=makeBrief(plan,e,pieces,ctx.preview?'recuperar negocio real; vista previa sin sincronización':ctx.negocioId);if(ctx.preview)$('briefText').value=$('briefText').value.replace('No se encontraron antecedentes registrados para este servicio en la lectura actual.','Historial no consultado en la vista previa. Debe recuperarse antes de redactar; no equivale a historial vacío.');openDialog('briefDialog')}
function showCoverage(){const f=filters(),service=f.service,eps=plan.episodes.filter(e=>!service||e.service===service),actual=pieces.filter(p=>!service||serviceMatches(p,service));let html=`<p>${service?esc(plan.services.find(s=>s.id===service).name):'Todos los servicios'} · ${eps.length} piezas previstas y ${ctx.preview?'historial no consultado':actual.length+' antecedentes'}. Aquí se muestran todas las audiencias y objetivos del servicio, independientemente de los demás filtros.</p><p><b>Previsto</b> es intención editorial. <b>Registrado</b> es uso en biblioteca; no equivale a publicado.</p>`;
 html+='<h3>Audiencia × objetivo</h3><div class="table-scroll"><table><thead><tr><th>Objetivo</th>'+audiences.map(a=>`<th>${short(a)}<br>previsto / registrado</th>`).join('')+'</tr></thead><tbody>'+objectives.map(o=>`<tr><th>${short(o)}</th>${audiences.map(a=>`<td>${`${eps.filter(e=>e.objective===o&&e.audience===a).length} / ${ctx.preview?'—':actual.filter(p=>p.objetivo===o&&p.temperatura===a).length}`}</td>`).join('')}</tr>`).join('')+'</tbody></table></div>';
 for(const [key,label,vals,actualKey] of [['motivation','Motivaciones',motivations,null],['category','Categorías',categories,'categoria'],['format','Formatos',formats,'formato'],['hook_candidates','Familias de hook propuestas',plan.hook_families.map(f=>f.id),'hook_family']]){html+=`<div class="coverage-section"><h3>${label}</h3><div class="table-scroll"><table><thead><tr><th>Opción</th><th>Previsto</th><th>Registrado</th><th>Qué falta</th></tr></thead><tbody>${coverage(eps,key,vals).map(({value,count})=>{const used=actual.filter(p=>actualKey?String(p[actualKey]||'').split('.')[0]===value:(p.metadata?.content_engine_v1?.topic_type||p.metadata?.editorial_context_v1?.motivation)===value).length;return `<tr><td>${esc(key==='category'?value+' · '+categoryLabels[value]:key==='hook_candidates'?value+' · '+plan.hook_families.find(f=>f.id===value).name:value)}</td><td>${count}</td><td>${ctx.preview?'—':used}</td><td>${count?'Desarrollar y verificar los guiones; previsto no es uso real.':value==='C5'?'Captura real y permiso según 20.':'Encontrar pregunta y recurso compatibles; sin cuota automática.'}</td></tr>`}).join('')}</tbody></table></div></div>`}
 html+=`<h3>Decisiones pendientes</h3><ul>${plan.coverage_notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul><h3>Propuestas todavía por investigar</h3><div class="history-list">${plan.reserve.filter(e=>!service||e.service===service).map(e=>`<div class="history-item"><b>${esc(e.question)}</b><small>${esc(e.reason)} Sin episodio ni fecha en esta edición.</small></div>`).join('')}</div><h3>Historial registrado</h3><div class="history-list">${actual.map(p=>`<div class="history-item"><a href="./biblioteca-contenido.html?negocio=${ctx.negocioId}&pieza=${p.id}">${esc(p.content_code+' · '+p.titulo)}</a><small>${esc(p.estado)} · ${esc(p.temperatura)} · ${esc(p.objetivo)}${p.temperatura==='RETORNO'?' · Clasificación heredada: RETORNO es relación; falta reclasificar temperatura.':''}</small></div>`).join('')||(ctx.preview?'Historial no consultado en la vista previa.':'No hay piezas registradas para este servicio.')}</div>`;$('coverageBody').innerHTML=html;openDialog('coverageDialog')}
async function readAll(table,columns){let out=[];for(let from=0;;from+=500){const {data,error}=await sb.from(table).select(columns).eq('negocio_id',ctx.negocioId).order('id').range(from,from+499);if(error)throw error;out.push(...data);if(data.length<500)return out}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close)$(b.dataset.close).close();if(b.dataset.service!==undefined){$('service').value=b.dataset.service;render();jumpNext()}if(b.dataset.episode)select(b.dataset.episode,true);if(b.dataset.detail)details(b.dataset.detail);if(b.dataset.brief)brief(b.dataset.brief)});
function jumpNext(){const eps=filterEpisodes(plan,filters()),e=eps.find(e=>e.key===selected)||eps[0];if(e?.reference_date){let d=date(e.reference_date),day=d.getUTCDay();anchor=plus(e.reference_date,-((day+6)%7));render()}}
for(const k of ['service','audience','objective','motivation'])$(k).onchange=()=>{render();jumpNext()};
$('reset').onclick=()=>{for(const k of ['audience','objective','motivation'])$(k).value='';render();jumpNext()};
$('previous').onclick=()=>{anchor=plus(anchor,-14);render()};$('next').onclick=()=>{anchor=plus(anchor,14);render()};$('nextDate').onclick=jumpNext;
$('coverageBtn').onclick=showCoverage;$('historyBtn').onclick=()=>{if(plan)showCoverage()};
$('download').onclick=()=>{const rows=[['Orden','Servicio','Colección','Parte','Total','Fecha referencial','Tema','Pregunta','Audiencia','Relación','Objetivo','Motivación','Categoría','Formato','Estado de evidencia','Estado de pieza'],...filterEpisodes(plan).map((e,i)=>[i+1,plan.services.find(s=>s.id===e.service).name,seriesFor(e).title,e.part,e.total,e.reference_date||'',e.title,e.question,e.audience,e.relationship,e.objective,e.motivation,categoryLabels[e.category],e.format,e.evidence_status,ctx.preview?'Historial no consultado':state(e).label])];const csv=rows.map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,m=>"'"+m).replaceAll('"','""')+'"').join(',')).join('\r\n');download('dr-olano-plan-editorial.csv','\uFEFF'+csv,'text/csv;charset=utf-8')};
$('copyBrief').onclick=async()=>{try{await navigator.clipboard.writeText($('briefText').value);notify('Pedido copiado. Pégalo en Chat 00.')}catch{$('briefText').focus();$('briefText').select();notify('Seleccioné el pedido para que puedas copiarlo.')}};
$('saveBrief').onclick=()=>download('pedido-chat00-'+selected+'.txt',$('briefText').value,'text/plain');
async function init(){try{ctx=await resolveContentContext();const requested=new URLSearchParams(location.search).get('negocio');if(!ctx.preview&&requested&&requested!==ctx.negocioId)throw Error('El negocio solicitado no está autorizado para esta sesión. Vuelve al panel y selecciona tu empresa.');$('business').textContent=ctx.negocio.nombre;if(!ctx.preview)for(const id of ['library','back'])$(id).href+='?negocio='+encodeURIComponent(ctx.negocioId);
 const {data,error}=await sb.from('content_planes_editoriales').select('id,negocio_id,plan_key,document,revision,updated_at').eq('negocio_id',ctx.negocioId).eq('plan_key','olano-editorial-v2').maybeSingle();if(error)throw error;if(!data)throw Error('Este negocio aún no tiene un plan editorial instalado.');record=data;plan=data.document;
 [pieces,publications]=await Promise.all([readAll('content_piezas','id,negocio_id,content_code,titulo,servicio,tema,objetivo,temperatura,categoria,formato,hook_family,hook_id,estado,approved_at,metadata'),readAll('content_publicaciones','id,negocio_id,content_id,estado,published_at,plataforma')]);
 picklist('service',plan.services.map(s=>({value:s.id,label:s.name})),'Todos');picklist('audience',audiences,'Todas');picklist('objective',objectives,'Todos');picklist('motivation',motivations,'Todas');const q=new URLSearchParams(location.search);for(const k of ['service','audience','objective','motivation'])$(k).value=q.get(k)||'';selected=q.get('tema');anchor=plan.start_date;$('edition').textContent=plan.edition;$('loading').hidden=true;$('app').hidden=false;render();jumpNext();
 }catch(err){$('loading').hidden=true;$('error').hidden=false;$('error').textContent=err.message||'No se pudo recuperar el plan. No se muestran contadores incompletos.'}}
init();
