(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.RecordingModel=api;})(typeof window!=='undefined'?window:this,function(){
 'use strict';
 const normalize=t=>String(t??'').replace(/\s+/g,' ').trim();
 function projectLabel(p){const ref=p?.metadata?.project_ref_v1,canonical=Number(ref?.project_number);if(!Number.isFinite(canonical)||canonical<3||!ref.project_created_at)return '';const visible=canonical-2,date=new Date(ref.project_created_at);if(!Number.isFinite(date.getTime()))return '';const parts=new Intl.DateTimeFormat('es-PE',{timeZone:'America/Lima',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date),g=t=>parts.find(x=>x.type===t)?.value;const months=['ENE','FEB','MAR','ABR','MAY','JUN','JUL','AGO','SEP','OCT','NOV','DIC'];return `PROYECTO ${String(visible).padStart(3,'0')} · ${g('day')}${months[Number(g('month'))-1]}${g('year')} · ${g('hour')}:${g('minute')}`;}
 function approvedView(p){try{const v=p?.metadata?.recording_view_v1,ref=p?.metadata?.project_ref_v1,revision=p?.metadata?.script_revision_v1;if(!v||v.schema_version!=='1.0'||v.project_id!==ref?.project_id||v.approved_script_version!==revision?.approved_script_version)return null;const seg=[...v.spoken_segments].sort((a,b)=>a.order-b.order),scenes=[...v.scenes].sort((a,b)=>a.narrative_order-b.narrative_order);if(!seg.length||new Set(seg.map(s=>s.segment_id)).size!==seg.length)return null;const text=normalize(seg.map(s=>s.text).join(' '));if(text!==normalize(p.master_script)||normalize(v.teleprompter_text)!==text)return null;const ids=scenes.filter(s=>s.scene_kind==='PRINCIPAL').flatMap(s=>s.spoken_segment_ids);if(JSON.stringify(ids)!==JSON.stringify(seg.map(s=>s.segment_id)))return null;const closing=seg[seg.length-1];if(closing.function!=='CLOSING'||closing.segment_id!==v.closing_segment_id||normalize(closing.text)!==normalize(p.cta_master)||!normalize(p.cta_master)||text.split(normalize(p.cta_master)).length!==2)return null;return {...v,spoken_segments:seg,scenes};}catch{return null;}}
 function spokenText(p){const v=approvedView(p);return v?v.spoken_segments.map(s=>s.text):String(p?.master_script||'').split(/\n+/).filter(s=>s.trim());}
 function sceneText(v,s){const map=new Map(v.spoken_segments.map(s=>[s.segment_id,s.text]));return(s.spoken_segment_ids||[]).map(id=>map.get(id)||'').join(' ');}
 return {normalize,projectLabel,approvedView,spokenText,sceneText};
});
